DROP TABLE IF EXISTS RESERVA;

CREATE TABLE RESERVA(
       DNI NUMERIC(8) REFERENCES CLIENTE(DNI) ON DELETE CASCADE,
       FECHA_SALIDA DATETIME,
       COD_AG NUMERIC REFERENCES AGENCIA(COD_AG),
       DESTINO TEXT,
       COD_VIAJE NUMERIC,
       IMPORTE NUMERIC(8,2),
       SEÑAL NUMERIC (8,2) CONSTRAINT IMPORTE_MINIMO CHECK(SEÑAL >= IMPORTE * 0.20),
       PRIMARY KEY (DNI, FECHA_SALIDA)
);
