DROP TABLE IF EXISTS PIEZAS;

CREATE TABLE PIEZAS(
       CODIGO TEXT PRIMARY KEY NOT NULL,
       NOM TEXT,
       COLOR TEXT,
       PESO NUMERIC,
       CIUDAD TEXT
);

INSERT INTO PIEZAS VALUES
('P1', 'TUERCA'   ,'ROJO'  ,12 ,'LONDRES'),
('P2', 'PERNO'    ,'VERDE' ,17 ,'PARIS'),
('P3', 'TORNILLO' ,'AZUL'  ,17 ,'ROMA'),
('P4', 'TORNILLO' ,'ROJO'  ,14 ,'LONDRES'),
('P5', 'LEVA'     ,'AZUL'  ,12 ,'PARIS'),
('P6', 'RUEDA'    ,'ROJO'  ,19 ,'LONDRES');
