DROP TABLE IF EXISTS PROVEEDORES;

CREATE TABLE PROVEEDORES(
       CODIGO TEXT PRIMARY KEY NOT NULL,
       NOM TEXT,
       ESTADO NUMERIC,
       CIUDAD TEXT
);

INSERT INTO PROVEEDORES VALUES
('S1', 'SALAZAR'   , 20 ,'LONDRES'),
('S2', 'JARAMILLO' , 10 ,'PARIS'),
('S3', 'BERNAL'    , 30 ,'PARIS'),
('S4', 'CAICEDO'   , 20 ,'LONDRES'),
('S5', 'ALDANA'    , 30 ,'ATENAS');
