DROP TABLE IF EXISTS PROYECTOS;

CREATE TABLE PROYECTOS(
       CODIGO TEXT PRIMARY KEY NOT NULL,
       NOM TEXT,
       CIUDAD TEXT
);

INSERT INTO PROYECTOS VALUES
('J1', 'CLASIFICADOR' ,'PARIS'),
('J2', 'PERFORADORA'  ,'ROMA'),
('J3', 'LECTORA'      ,'ATENAS'),
('J4', 'CONSOLA'      ,'ATENAS'),
('J5', 'COMPAGINADOR' ,'LONDRES'),
('J6', 'TERMINAL'     ,'OSLO'),
('J7', 'CINTA'        ,'LONDRES');


