CREATE TABLE DEPORTISTA (
       COD_DEPORTISTA NUMERIC PRIMARY KEY NOT NULL,
       NOMBRE TEXT NOT NULL,
       NACIONALIDAD TEXT,
       ALTURA NUMERIC,
       FECHA_NAC DATE CONSTRAINT NACE CHECK(FECHA_NAC > 31/12/1960),
       NIVEL TEXT,
       COD_DEP_ENTRENADOR NUMERIC REFERENCES DEPORTISTA(COD_DEPORTISTA)
);
